// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package todos

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
  title, description, done
) VALUES (
  $1, $2, $3
)
RETURNING id, done, title, description, created_at
`

type CreateTodoParams struct {
	Title       sql.NullString
	Description sql.NullString
	Done        sql.NullBool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.Title, arg.Description, arg.Done)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Done,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :one
DELETE FROM todos
WHERE id = $1
RETURNING id, done, title, description, created_at
`

func (q *Queries) DeleteTodo(ctx context.Context, id int32) (Todo, error) {
	row := q.db.QueryRowContext(ctx, deleteTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Done,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, done, title, description, created_at FROM todos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTodo(ctx context.Context, id int32) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Done,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, done, title, description, created_at FROM todos
ORDER BY created_at
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Done,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
  set title = $2,
  description = $3,
  done = $4
WHERE id = $1
RETURNING id, done, title, description, created_at
`

type UpdateTodoParams struct {
	ID          int32
	Title       sql.NullString
	Description sql.NullString
	Done        sql.NullBool
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Done,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Done,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
